name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    coding-standards:
        name: "Coding Standards"

        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2.3.4"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@2.9.0"
                with:
                    coverage: "none"
                    extensions: "mbstring"
                    php-version: "8.0"
                    tools: "composer-normalize"

            -   name: "Validate composer.json"
                run: "composer validate --strict"

            -   name: "Normalize composer.json"
                run: "composer-normalize --dry-run"

    tests:
        name: "Tests"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.0"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2.3.4"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@2.9.0"
                with:
                    coverage: "none"
                    extensions: "mbstring"
                    php-version: "${{ matrix.php-version }}"

            -   name: "Install dependencies with composer"
                run: "composer update --no-interaction --no-progress"

            -   name: "Run unit tests"
                run: "vendor/bin/phpunit"
